server:
  port: ${PORT:8096}

# Configuração global — aplicada a TODOS os microserviços
spring:
  application:
    name: combat-api

  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: combat_db
      username: ${MONGO_ROOT_USER:admin}
      password: ${MONGO_ROOT_PASS}
      authentication-database: admin

logging:
  level:
    root: INFO
    br.com.study.combatapi: DEBUG